server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/library?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: sise
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-wait-millis: 360000
      max-total: 5
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        min-idle: 5
        max-idle: 10
    password: sise
#  mail:
#    host: smtp.qq.com
#    username: xxx@qq.com
#    password: xxx
#    properties:
#      mail:
#        smtp:
#          auth: true  # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
#          starttls:
#            enable: true
#            required: true
#    default-encoding: UTF-8
#    protocol: smtp
#    port: 587

mybatis:
  type-aliases-package: com.ripen.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    use-column-label: true
#nginx图片配置
#ftp:
#  host: ip
#  userName: xxx
#  password: xxxx
#  port: 22
#  rootPath: /usr/nginx/image/shop/
#  img:
#    url: http://ip:端口/shop/